name: Docker Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Lint with flake8
      run: |
        pip install flake8
        # Зупинити збірку якщо є синтаксичні помилки або невизначені імена
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Попередження про складність коду
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      continue-on-error: true
    
    - name: Test imports
      run: |
        # Перевіряємо чи можна імпортувати основні модулі
        python -c "
        import sys
        sys.path.append('src')
        try:
            from models.user import UserDatabase, User
            from services.steam_api import SteamAPI
            from services.daily_reports import DailyReportsService
            print('✅ Всі імпорти працюють')
        except ImportError as e:
            print(f'❌ Помилка імпорту: {e}')
            sys.exit(1)
        "

  docker-build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: cs2-stats-bot:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Test Docker image
      run: |
        # Тестуємо чи образ збирається та запускається
        docker run --rm \
          -e TELEGRAM_BOT_TOKEN="test_token" \
          -e STEAM_API_KEY="test_key" \
          -e DATABASE_PATH="/app/data/test.db" \
          --entrypoint="" \
          cs2-stats-bot:test \
          python -c "
        import sys
        sys.path.append('/app')
        try:
            from src.models.user import UserDatabase
            from src.services.steam_api import SteamAPI
            print('✅ Docker образ працює правильно')
        except Exception as e:
            print(f'❌ Помилка в Docker образі: {e}')
            sys.exit(1)
        "
    
    - name: Check Docker image size
      run: |
        docker images cs2-stats-bot:test
        IMAGE_SIZE=$(docker images cs2-stats-bot:test --format "{{.Size}}")
        echo "📊 Розмір образу: $IMAGE_SIZE"

  security-scan:
    needs: docker-build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: cs2-stats-bot:test
        format: 'sarif'
        output: 'trivy-results.sarif'
      continue-on-error: true
    
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'
      continue-on-error: true
